//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyRates.Web.CurrencyRatesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyRatesService.ICurrencyRatesService")]
    public interface ICurrencyRatesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyRatesService/Find", ReplyAction="http://tempuri.org/ICurrencyRatesService/FindResponse")]
        CurrencyRates.Model.Entities.Rate Find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyRatesService/Find", ReplyAction="http://tempuri.org/ICurrencyRatesService/FindResponse")]
        System.Threading.Tasks.Task<CurrencyRates.Model.Entities.Rate> FindAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyRatesService/FindLatest", ReplyAction="http://tempuri.org/ICurrencyRatesService/FindLatestResponse")]
        CurrencyRates.Model.Entities.Rate[] FindLatest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyRatesService/FindLatest", ReplyAction="http://tempuri.org/ICurrencyRatesService/FindLatestResponse")]
        System.Threading.Tasks.Task<CurrencyRates.Model.Entities.Rate[]> FindLatestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyRatesServiceChannel : CurrencyRates.Web.CurrencyRatesService.ICurrencyRatesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyRatesServiceClient : System.ServiceModel.ClientBase<CurrencyRates.Web.CurrencyRatesService.ICurrencyRatesService>, CurrencyRates.Web.CurrencyRatesService.ICurrencyRatesService {
        
        public CurrencyRatesServiceClient() {
        }
        
        public CurrencyRatesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyRatesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyRatesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyRatesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CurrencyRates.Model.Entities.Rate Find(int id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<CurrencyRates.Model.Entities.Rate> FindAsync(int id) {
            return base.Channel.FindAsync(id);
        }
        
        public CurrencyRates.Model.Entities.Rate[] FindLatest() {
            return base.Channel.FindLatest();
        }
        
        public System.Threading.Tasks.Task<CurrencyRates.Model.Entities.Rate[]> FindLatestAsync() {
            return base.Channel.FindLatestAsync();
        }
    }
}
